#!/bin/bash
set -e

git fetch
git merge --ff-only origin/master
rm -rf node_modules/
npm install --production
grunt compile-less
docker stop huburn
docker rm huburn
docker run -d -p 8080:8080 -v $PWD:/huburn --name="huburn" huburn-image
