#!/bin/bash
set -e

git fetch
git merge --ff-only origin/master
grunt compile-less
docker stop huburn
docker rm huburn
docker run -d -p 80:8080 -p 443:8443 -v $PWD:/huburn --name="huburn" huburn-image
